apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-kube
  labels:
    app: rust-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-kube
  template:
    metadata:
      labels:
        app: rust-kube
    spec:
      containers:
        - name: rust-kube
          imagePullPolicy: Never
          image: rust-kube:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: cloud-logging-service-account
              mountPath: /app/env/cloud-logging
      volumes:
        - name: cloud-logging-service-account
          secret:
            secretName: cloud-logging-service-account-755h7c7kbg
